### ISSUE TITLE
logisticModel.ipynb

### ISSUE THREAD

**Issue by tobias-fritz** [eloyvallinaes/protein-physics-2022#1]
In the  logistic model notebook [the equation](https://github.com/eloyvallinaes/protein-physics-2022/blob/58f0150db9b7b0d77f9bd5a6029479ed9512f0ff/logisticModel.ipynb?short_path=62bfccc#L275) the function is implemented using the natural logarithm instead of lg.

**Comment by eloyvallinaes** [comment]
Thanks for the headsup!

**Comment by eloyvallinaes** [comment]
Fixed on `f7d5df2`
